### ISSUE TITLE
经常出现断续不能读的问题

### ISSUE THREAD

**Issue by zxssaa** [ag2s20150909/TTS#119]
最近在使用中，读一段时间，然后就没有声音了，等一会儿，会自动跳到文章的下一段又开始读有声音了。
然后再读一会儿又没有声音了，不管它等一会儿，还是跳到下一段文字开始读。
没有声音的时候，软件在通知栏里是没有报错的，显示的还是要读的文本，但是没有声音。
还有其他人存在这样问题么？

**Comment by ghost** [comment]
都有，是网络延时吧，转换传输需要时间，大段、换页时较明显，软件逻辑有待优化。
测试感觉默认mp3较为流畅，理论低延时的opus实际体验一般；
将换页模式改为滚动，听听是否改善？我不确定是否心理作用。

讯飞有声没这种问题，朗读者角色很丰富鲜明，语气换气自然度略逊于微软TTS，第三方APP调用讯飞引擎的效果较差。

**Comment by zycboss** [comment]
我用静读天下，一样的问题，基本上连续读3-5分钟就会卡住，不知道在等什么，暂停，重新朗读，又好了
各种网络环境都试过了，wifi，4g，开梯子，不开梯子，全都是一样，以前不会这么频繁卡住，就今年9月份更新以后才开始这样的
试过换各种音频流格式也无法解决，静读天下更新版本也无法解决

**Comment by cool-delete** [comment]
同+1
我用阅读3.0也是断断续续的 会卡个2-3分钟才会自动读下去

**Comment by srxy2252** [comment]
同样问题+1
使用的是阅读3.0，隔几分钟就卡主

**Comment by KnIfER** [comment]
这里doDecode出错时，回调done而不是error是否好一些

https://github.com/ag2s20150909/TTS/blob/7b36cdf2969ba4fd403f9d3e02d9476d4819e79d/app/src/main/java/me/ag2s/tts/services/TTSService.java#L538

貌似如果出现不支持字符就会出错，就收不到done回调

**Comment by KnIfER** [comment]
```
2022-12-08 20:57:29.981 30542-1016/me.ag2s.tts I/fatal poison: 套接字:: TTS服务-失败中 onFailure null java.io.EOFExceptionjava.io.EOFException
        at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
        at okio.RealBufferedSource.readByte(RealBufferedSource.kt:209)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
        at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:535)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2022-12-08 20:57:29.993 30542-1016/me.ag2s.tts I/fatal poison: sendConfig::sending…… X-Timestamp:+Thu Dec 08 2022 20:57:29 GMT+0800
    Content-Type:application/json; charset=utf-8
    Path:speech.config
    
    {"context":{"synthesis":{"audio":{"metadataoptions":{"sentenceBoundaryEnabled":"false","wordBoundaryEnabled":"true"},"outputFormat":"raw-16khz-16bit-mono-pcm"}}}} 
2022-12-08 20:57:30.995 30542-1341/me.ag2s.tts I/fatal poison: 套接字:: onOpen:: Connection: Upgrade
    Date: Thu, 08 Dec 2022 12:57:28 GMT
    Server: Microsoft-IIS/10.0
    Access-Control-Allow-Credentials: true
    Access-Control-Allow-Origin: https://azure.microsoft.com
    Set-Cookie: ██
    Set-Cookie: ██
    Upgrade: websocket
    Vary: Origin
    X-RateLimit-Limit: 200
    X-RateLimit-Remaining: 151
    X-RateLimit-Reset: 2022-12-09T12:57:28Z
    Sec-WebSocket-Accept: GkuJKws/mjWeC8hjWK4DdkLK4Ps=
    Strict-Transport-Security: max-age=2592000; includeSubdomains; preload
    X-Frame-Options: SAMEORIGIN
    Content-Security-Policy: frame-ancestors 'self'
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff
    Referrer-Policy: no-referrer
```
这是什么，eof后会卡住，

**Comment by srxy2252** [comment]
根据前面的建议关闭了预览语音选项就好了，基本上不会断了

**Comment by KnIfER** [comment]
确实是预览语音

**Comment by zycboss** [comment]
预览语音关了直接没法朗读了何解？必须也关掉自定义才行，关掉自定义就没有朗读风格了，只有默认的语音，我只想要晓秋…

**Comment by KnIfER** [comment]
![image](https://user-images.githubusercontent.com/11593903/206691505-62e0b378-a4d1-4995-b191-751098edc743.png)

哈哈，偶是添柴

我也要发个魔法修改版出来，感谢原作大佬！

是叫 TTSPro 还是 TTSHub 好呢……

**Comment by zycboss** [comment]
最近几天似乎好了，断的没有以前频繁了，经常能连续读挺久，什么设置都没改，那么这是微软那边的问题？

**Comment by rose07** [comment]
> 最近在使用中，读一段时间，然后就没有声音了，等一会儿，会自动跳到文章的下一段又开始读有声音了。 然后再读一会儿又没有声音了，不管它等一会儿，还是跳到下一段文字开始读。 没有声音的时候，软件在通知栏里是没有报错的，显示的还是要读的文本，但是没有声音。 还有其他人存在这样问题么？

可以试试这个网站的,也是微软的
https://tts.byylook.com/ai/text-to-speech

**Comment by rose07** [comment]
> 最近在使用中，读一段时间，然后就没有声音了，等一会儿，会自动跳到文章的下一段又开始读有声音了。 然后再读一会儿又没有声音了，不管它等一会儿，还是跳到下一段文字开始读。 没有声音的时候，软件在通知栏里是没有报错的，显示的还是要读的文本，但是没有声音。 还有其他人存在这样问题么？

https://tts.byylook.com/ai/text-to-speech

**Comment by Icecrap** [comment]
亲测有效的方法：

先在multitts软件内打开转发服务，然后在软件设置，在选项内选择添至阅读（点我添加转发服务至阅读），然后在阅读软件内选择multitts·转发器，选择全局，设置完毕后，再重新点朗读功能，便可以零延迟一直朗读，不会暂停

**Comment by Icecrap** [comment]
亲测有效的方法：

先在multitts软件内打开转发服务，然后在软件设置，在选项内选择添至阅读（点我添加转发服务至阅读），然后在阅读软件内选择multitts·转发器，选择全局，设置完毕后，再重新点朗读功能，便可以零延迟一直朗读，不会暂停
