### ISSUE TITLE
因排序代码bug导致部分系统闪退

### ISSUE THREAD

**Issue by rosiaruuretto** [ag2s20150909/TTS#68]
部分安卓系统打开时无故闪退，经查系：
```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
 	at java.util.TimSort.mergeLo(TimSort.java:777)
 	at java.util.TimSort.mergeAt(TimSort.java:514)
 	at java.util.TimSort.mergeCollapse(TimSort.java:441)
 	at java.util.TimSort.sort(TimSort.java:245)
 	at java.util.Arrays.sort(Arrays.java:1492)
 	at java.util.ArrayList.sort(ArrayList.java:1470)
 	at java.util.Collections.sort(Collections.java:206)
 	at me.ag2s.tts.services.TtsActorManger.sortByLocale(TtsActorManger.java:511)
 	at me.ag2s.tts.services.TtsActorManger.getActorsByLocale(TtsActorManger.java:593)
```

将 `TtsActorManger.sortByLocale()` 中排序代码删除，直接改为无动作函数可临时解决问题

**Comment by ag2s20150909** [comment]
> 部分安卓系统打开时无故闪退，经查系：
> 
> ```
> java.lang.IllegalArgumentException: Comparison method violates its general contract!
>  	at java.util.TimSort.mergeLo(TimSort.java:777)
>  	at java.util.TimSort.mergeAt(TimSort.java:514)
>  	at java.util.TimSort.mergeCollapse(TimSort.java:441)
>  	at java.util.TimSort.sort(TimSort.java:245)
>  	at java.util.Arrays.sort(Arrays.java:1492)
>  	at java.util.ArrayList.sort(ArrayList.java:1470)
>  	at java.util.Collections.sort(Collections.java:206)
>  	at me.ag2s.tts.services.TtsActorManger.sortByLocale(TtsActorManger.java:511)
>  	at me.ag2s.tts.services.TtsActorManger.getActorsByLocale(TtsActorManger.java:593)
> ```
> 
> 将 `TtsActorManger.sortByLocale()` 中排序代码删除，直接改为无动作函数可临时解决问题

Android M 以下系统将不排序
